language: python
python:
  - "3.6"
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - pip install -r requirements-dev.txt
  - pip install pytest-cov codecov
# command to run tests
script:
  - pytest --cov="tornado_jsonrpc2"
  - codecov
