language: python
cache: pip
python:
  - "3.6"
  - "3.7"

install:
  - pip install -e .[test]
  - pip install pytest-cov codecov

script:
  - pytest --cov="tornado_jsonrpc2" --cov-report term-missing tests/
  - codecov
