language: python
cache: pip
dist: xenial
python:
  - "3.6"
  - "3.7"

env:
  - TORNADO_VERSION=5
  - TORNADO_VERSION=6

install:
  - pip install tornado~=$TORNADO_VERSION
  - pip install -e .[test]
  - pip install pytest-cov codecov

script:
  - pytest --cov="tornado_jsonrpc2" --cov-report term-missing tests/
  - codecov
